site_name: AzStuff â¤ï¸
site_description: Azure Stuff
site_author: JosÃ© CABEZA

repo_url: https://github.com/jcabeza/AzStuff
repo_name: jcabeza/AzStuff
edit_uri: edit/main/docs/

theme:
  name: material
  favicon: _assets/azure.png
  logo: ğŸ¤– #_assets/azure.png
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  highlightjs: true
  
extra_css:
    - _stylesheets/extra.css

plugins:
  - search
  #- git-revision-date
  #- encryptcontent

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jcabeza
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jcabeza_1

nav:
  - ğŸ  Home: 'index.md'
  - ğŸ“’ Guide:
    - Azure Architecture: ./guides/azure-architecture.md
    - Azure Migration: ./guides/azure-migration.md
  - ğŸª› Stuff:
    - Status pages: ./stuff/status-pages.md
    - Azure tools: ./stuff/azure-tools.md
    - DevOps tools: ./stuff/devops-tools.md
    - Stencils & icons: ./stuff/stencils-icons.md
  - ğŸ“ Learn:
    - Azure: ./learn/azure-learn.md
    - DevOps: ./learn/devops-learn.md
    - Hashicorp: ./learn/hashicorp-learn.md
    - Kubernetes: ./learn/kubernetes-learn.md
  - ğŸ“– ToRead:
    - Articles: ./to-read/articles.md
  - ğŸ§‘â€ğŸ’» Team:
    - Contributors: ./team/contributors.md
  - ğŸ§ª POC:
    - Deploy to Azure: ./poc/deploy-to-azure.md